language: go
go:
  - 1.4.2
install:
  - go get golang.org/crypto/blowfish
  - go get golang.org/crypto/cast5
  - go get golang.org/crypto/salsa20
  - go get github.com/codahale/chacha20
  - go install ./cmd/shadowsocks-local
  - go install ./cmd/shadowsocks-server
script:
  - PATH=$PATH:$HOME/gopath/bin bash -x ./script/test.sh
